apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-unwb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-unwb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-unwb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-unwb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-unwb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oobl-tenant/rhtap-demo-app/hacbs-test-project-unwb@sha256:ffe1a79e6e782e228acb4827b569c6f414863dcc7c887227e3c868680c077cc9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
